In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf

In [2]:
### INTRO TO BUILDING A GRAPH IN TF


graph = tf.Graph()
m1 = np.array([[1.,2.],[3.,4.],[5.,6.],[7.,8.]], dtype=np.float32)


with graph.as_default():
    
    m1_input = tf.placeholder(tf.float32, shape=[4,2])
    
    
    with tf.device('/cpu:0'):
        
        m2 = tf.Variable(tf.random_uniform([2,3], -1.0, 1.0))
        
        m3 = tf.matmul(m1_input, m2)
        
        m4 = tf.add(m3, m3)
        
        init = tf.initialize_all_variables()

with tf.Session(graph=graph) as session:
    
    init.run()
    print("Initialized")
    
    print("m2: \n{}".format(m2))
    print("eval m2: \n{}".format(m2.eval()))
    
    feed_dict = {m1_input: m1}
    
    result3, result4 = session.run([m3, m4], feed_dict=feed_dict)
    print("\nresult: \n{}\nresult doubled: \n{}\n".format(result3, result4))

Initialized
m2: 
eval m2: 
[[-0.86933422 -0.81694651 -0.89179397]
 [-0.94384623  0.18375397  0.31771255]]

result: 
[[ -2.75702667  -0.44943857  -0.25636888]
 [ -6.38338757  -1.71582365  -1.40453172]
 [-10.00974846  -2.98220873  -2.5526948 ]
 [-13.63610935  -4.24859381  -3.70085716]]
result doubled: 
[[ -5.51405334  -0.89887714  -0.51273775]
 [-12.76677513  -3.4316473   -2.80906343]
 [-20.01949692  -5.96441746  -5.1053896 ]
 [-27.2722187   -8.49718761  -7.40171432]]



In [ ]:
### word2vec Vector representation of words

